server.servlet.context-path=/techspace

spring.datasource.name=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
